"""
load_to_mongo.py — CSV → MongoDB ETL for user_engagements collection.

Reads the 9 CSV files generated by build_csvs.py, denormalizes them,
groups by user, and bulk-inserts into MongoDB.

Why CSV instead of MySQL?
─────────────────────────
With 10M+ rows in impressions.csv (900MB), CSV is the better choice:
  • pd.read_csv is ~3-10x faster than pd.read_sql for full table reads
    (no network overhead, no SQL parsing, no type negotiation)
  • Small lookups (countries, campaigns, etc.) are loaded into dicts first,
    then impressions are streamed in chunks and denormalized via vectorized
    pandas operations — no slow row-by-row iteration
  • No dependency on MySQL container being healthy during the load

Strategy:
  1. Load small lookup CSVs fully into memory (countries, interests, etc.)
  2. Build clicks lookup dict (impression_id → click list)
  3. Load users → build base user docs dict
  4. Stream impressions.csv in chunks → vectorized merge with lookups →
     group by user_id → append impression arrays to user docs
  5. Bulk insert user docs into MongoDB in batches
"""

import pandas as pd
from pymongo import MongoClient
from datetime import datetime
from dotenv import load_dotenv
import time
import os
import sys

# Load .env file from current directory (or parent)
load_dotenv()  # looks for .env in cwd
load_dotenv(dotenv_path=os.path.join("..", ".env"))  # also check parent dir

# ──────────────────────────────────────────────
# CONFIG — adjust paths to where your CSVs live
# ──────────────────────────────────────────────
CSV_DIR = os.environ.get("CSV_DIR", "../csv_files_v2")  # default: current directory

# Build MongoDB URI from .env variables
_mongo_user = os.environ.get("MONGO_INITDB_ROOT_USERNAME", "root")
_mongo_pass = os.environ.get("MONGO_INITDB_ROOT_PASSWORD", "mongopass")
MONGO_URI = os.environ.get(
    "MONGO_URI",
    f"mongodb://{_mongo_user}:{_mongo_pass}@localhost:27017/"
)
MONGO_DB = os.environ.get("MONGO_DB", "adtech_db")
COLLECTION = "user_engagements"

CHUNK_SIZE = 200_000  # rows per chunk for impressions.csv


def fmt_time(seconds):
    """Format seconds into human-readable string."""
    if seconds < 60:
        return f"{seconds:.0f}s"
    m, s = divmod(int(seconds), 60)
    if m < 60:
        return f"{m}m {s}s"
    h, m = divmod(m, 60)
    return f"{h}h {m}m {s}s"


def progress_bar(current, total, width=30, prefix="", extra=""):
    """Print an inline progress bar. Near-zero overhead."""
    pct = current / total if total else 0
    filled = int(width * pct)
    bar = "█" * filled + "░" * (width - filled)
    line = f"\r  {prefix}|{bar}| {pct:5.1%}  {current:,}/{total:,}  {extra}"
    sys.stdout.write(line)
    sys.stdout.flush()


def load_csv(name, **kwargs):
    """Load a CSV from CSV_DIR with timing."""
    path = os.path.join(CSV_DIR, name)
    if not os.path.exists(path):
        print(f"  ✗ {name} — FILE NOT FOUND at {path}")
        sys.exit(1)
    print(f"  Loading {name}...", end=" ", flush=True)
    t = time.time()
    df = pd.read_csv(path, engine="pyarrow", **kwargs)
    elapsed = time.time() - t
    print(f"{len(df):,} rows ({elapsed:.1f}s)")
    return df


def main():
    t_start = time.time()

    # ─── 1. Connect to MongoDB ───
    print("\n═══ Connecting to MongoDB ═══")
    client = MongoClient(MONGO_URI)
    db = client[MONGO_DB]
    col = db[COLLECTION]

    existing = col.count_documents({})
    if existing > 0:
        print(f"  Collection has {existing:,} docs — dropping for clean reload...")
        col.delete_many({})

    # ─── 2. Load small lookup tables ───
    print("\n═══ Loading lookup CSVs ═══")
    countries = load_csv("countries.csv")
    interests = load_csv("interests.csv")
    advertisers = load_csv("advertisers.csv")
    campaigns = load_csv("campaigns.csv")
    users = load_csv("users_fact.csv")
    user_interests = load_csv("user_interests.csv")
    clicks_df = load_csv("clicks.csv")

    # ─── 3. Build lookup dicts (fast O(1) access) ───
    print("\n═══ Building lookup dictionaries ═══")

    country_map = dict(zip(countries["country_id"], countries["country_name"]))
    interest_map = dict(zip(interests["interest_id"], interests["interest_name"]))
    advertiser_map = dict(zip(advertisers["advertiser_id"], advertisers["advertiser_name"]))

    # campaign_id → (campaign_name, advertiser_name)
    camp_merged = campaigns.merge(advertisers, on="advertiser_id", how="left")
    campaign_name_map = dict(zip(camp_merged["campaign_id"], camp_merged["campaign_name"]))
    campaign_adv_map = dict(zip(camp_merged["campaign_id"], camp_merged["advertiser_name"]))

    # user_id → [interest names]
    ui_merged = user_interests.merge(interests, on="interest_id", how="left")
    user_interest_names = (
        ui_merged.groupby("user_id")["interest_name"]
        .apply(list)
        .to_dict()
    )

    print(f"  {len(country_map):,} countries, {len(campaign_name_map):,} campaigns")

    # ─── 4. Build clicks index: impression_id → [click dicts] ───
    print("\n═══ Building clicks index ═══")
    t_clicks = time.time()

    # clicks.csv columns: click_id, impression_id, click_timestamp, ad_revenue
    clicks_df["click_timestamp"] = pd.to_datetime(clicks_df["click_timestamp"], errors="coerce")
    clicks_by_imp = {}
    n_clicks = len(clicks_df)
    for i, (imp_id, grp) in enumerate(clicks_df.groupby("impression_id")):
        clicks_by_imp[str(imp_id)] = [
            {
                "click_id": str(row["click_id"]),
                "click_timestamp": row["click_timestamp"].to_pydatetime()
                    if pd.notna(row["click_timestamp"]) else None,
                "ad_revenue": float(row["ad_revenue"]) if pd.notna(row["ad_revenue"]) else 0.0,
            }
            for _, row in grp.iterrows()
        ]
        if (i + 1) % 50000 == 0:
            progress_bar(i + 1, n_clicks, prefix="Clicks: ")

    print(f"\n  ✓ {len(clicks_by_imp):,} impressions have clicks ({fmt_time(time.time() - t_clicks)})")

    # ─── 5. Build base user documents ───
    print("\n═══ Building user documents ═══")
    t_users = time.time()

    user_docs = {}
    n_users = len(users)
    for i, (_, u) in enumerate(users.iterrows()):
        uid = int(u["user_id"])
        user_docs[uid] = {
            "_id": uid,
            "age": int(u["age"]),
            "gender": str(u["gender"]),
            "country": country_map.get(int(u["country_id"]), "Unknown"),
            "signup_date": datetime.strptime(str(u["signup_date"]), "%Y-%m-%d"),
            "interests": user_interest_names.get(uid, []),
            "impressions": [],
        }
        if (i + 1) % 50000 == 0 or i + 1 == n_users:
            progress_bar(i + 1, n_users, prefix="Users: ")

    print(f"\n  ✓ {len(user_docs):,} users prepared ({fmt_time(time.time() - t_users)})")

    # ─── 6. Stream impressions.csv in chunks (vectorized) ───
    print(f"\n═══ Processing impressions.csv in {CHUNK_SIZE:,}-row chunks ═══")

    imp_path = os.path.join(CSV_DIR, "impressions.csv")
    total_imp = 0
    chunk_num = 0

    # Count total rows first for ETA (fast — just counts newlines)
    print("  Counting rows in impressions.csv...", end=" ", flush=True)
    with open(imp_path, "r") as f:
        total_rows = sum(1 for _ in f) - 1  # minus header
    total_chunks = (total_rows + CHUNK_SIZE - 1) // CHUNK_SIZE
    print(f"{total_rows:,} rows ({total_chunks} chunks)")

    chunk_times = []  # track per-chunk time for ETA
    errors = []       # collect any row-level issues

    for chunk in pd.read_csv(imp_path, chunksize=CHUNK_SIZE, engine="c"):
        chunk_num += 1
        total_imp += len(chunk)
        t_chunk = time.time()

        # ── Vectorized denormalization using .map() ──
        imp_ids = chunk["impression_id"].astype(str).values
        camp_ids = chunk["campaign_id"].values
        user_ids = chunk["user_id"].values
        ad_slots = chunk["ad_slot_size"].astype(str).values
        devices = chunk["device"].astype(str).values
        country_ids = chunk["served_country_id"].values
        timestamps = pd.to_datetime(chunk["event_timestamp"], errors="coerce").values
        bids = chunk["bid_amount"].values
        costs = chunk["ad_cost"].values

        # ── Pure Python loop over numpy arrays (no pandas overhead) ──
        for i in range(len(chunk)):
            uid = int(user_ids[i])
            if uid not in user_docs:
                errors.append(f"user_id={uid} not found")
                continue

            imp_id = str(imp_ids[i])
            ts = timestamps[i]
            ts_py = pd.Timestamp(ts).to_pydatetime() if not pd.isna(ts) else None

            impression_doc = {
                "impression_id": imp_id,
                "campaign_id": int(camp_ids[i]),
                "campaign_name": campaign_name_map.get(int(camp_ids[i]), "Unknown"),
                "advertiser_name": campaign_adv_map.get(int(camp_ids[i]), "Unknown"),
                "ad_slot_size": str(ad_slots[i]),
                "device": str(devices[i]),
                "country_served": country_map.get(int(country_ids[i]), "Unknown"),
                "timestamp": ts_py,
                "bid_amount": float(bids[i]),
                "ad_cost": float(costs[i]),
                "clicks": clicks_by_imp.get(imp_id, []),
            }
            user_docs[uid]["impressions"].append(impression_doc)

        elapsed = time.time() - t_chunk
        chunk_times.append(elapsed)
        avg_chunk = sum(chunk_times) / len(chunk_times)
        remaining = (total_chunks - chunk_num) * avg_chunk
        eta_str = fmt_time(remaining) if remaining > 0 else "done"
        progress_bar(
            chunk_num, total_chunks,
            prefix="Imps: ",
            extra=f"{elapsed:.1f}s/chunk  ETA: {eta_str}   "
        )

    # Print any errors collected
    print(f"\n  ✓ Total impressions processed: {total_imp:,}")
    if errors:
        unique_errors = list(set(errors))
        print(f"  ⚠ {len(errors)} warnings ({len(unique_errors)} unique):")
        for e in unique_errors[:10]:  # show max 10
            print(f"    - {e}")
        if len(unique_errors) > 10:
            print(f"    ... and {len(unique_errors) - 10} more")

    # ─── 7. Bulk insert into MongoDB ───
    # Filter out users with 0 impressions (optional — include them if you want)
    docs = [d for d in user_docs.values()]
    users_with_imps = sum(1 for d in docs if d["impressions"])
    print(f"\n═══ Inserting {len(docs):,} users ({users_with_imps:,} have impressions) ═══")

    BATCH = 500
    inserted = 0
    failed = []
    t_insert = time.time()
    total_batches = (len(docs) + BATCH - 1) // BATCH

    for i in range(0, len(docs), BATCH):
        batch = docs[i : i + BATCH]
        batch_num = i // BATCH + 1
        try:
            col.insert_many(batch, ordered=False)
            inserted += len(batch)
        except Exception as e:
            print(f"\n  ⚠ Batch {batch_num} error: {e}")
            for doc in batch:
                try:
                    col.insert_one(doc)
                    inserted += 1
                except Exception as e2:
                    failed.append((doc["_id"], str(e2)))

        elapsed_ins = time.time() - t_insert
        avg_batch = elapsed_ins / batch_num
        eta_ins = (total_batches - batch_num) * avg_batch
        progress_bar(
            inserted, len(docs),
            prefix="Insert: ",
            extra=f"ETA: {fmt_time(eta_ins)}   "
        )

    t_insert_done = time.time()

    if failed:
        print(f"\n  ⚠ {len(failed)} documents failed to insert:")
        for uid, err in failed[:10]:
            print(f"    _id={uid}: {err}")
        if len(failed) > 10:
            print(f"    ... and {len(failed) - 10} more")

    # ─── 8. Summary ───
    t_end = time.time()
    final_count = col.count_documents({})

    print(f"\n\n═══════════════════════════════")
    print(f"  ✓ DONE")
    print(f"  Documents in collection: {final_count:,}")
    print(f"  Insert time:  {fmt_time(t_insert_done - t_insert)}")
    print(f"  Total time:   {fmt_time(t_end - t_start)}")
    print(f"═══════════════════════════════")

    # Quick sanity check — show a sample document
    sample = col.find_one({"impressions.0": {"$exists": True}})
    if sample:
        n_imps = len(sample.get("impressions", []))
        n_clicks = sum(1 for imp in sample["impressions"] if imp.get("clicks"))
        print(f"\n  Sample user _id={sample['_id']}:")
        print(f"    Age={sample['age']}, Gender={sample['gender']}, Country={sample['country']}")
        print(f"    Interests: {sample['interests']}")
        print(f"    Impressions: {n_imps:,}, with clicks: {n_clicks:,}")

    client.close()


if __name__ == "__main__":
    main()